# Configurations
title:            NYX Blog
longtitle:        NYX Blog 2
author:           d4t4s3c
email:            mail@vulnyx.com
description: >
  The hacker blog full of tricks for the playground.

version:          1.0
gitbook_version:  3.2.3

url:              'https://vulnyx.github.io'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: vulnyx/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     ../assets/gitbook/images/favicon.png

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: github

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                 /:categories/:title

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:

ordered_collections:

# default 800px
page_width: 1000px

destination:      ./_site
incremental:      false
regenerate:       true

# fix to accept future years (will allow using the year as an ID to sort items)
future:           true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
